# Generated by Django 3.2.3 on 2021-07-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parte2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='question1',
            field=models.CharField(max_length=120, verbose_name='How many teams race in Formula 1?'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question10',
            field=models.CharField(max_length=120, verbose_name='How many championships has Lewis Hamilton won?'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question2',
            field=models.CharField(max_length=120, verbose_name='How many championships has Lewis Hamilton won?'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question3',
            field=models.CharField(max_length=120, verbose_name='Which Team has won the most championships?'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question4',
            field=models.CharField(max_length=120, verbose_name='For which team does Nicholas Latifi race for?'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question5',
            field=models.CharField(max_length=120, verbose_name='What color is the Ferrari car?'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question6',
            field=models.CharField(max_length=120, verbose_name="Where is the location of Haas's base?"),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question7',
            field=models.CharField(max_length=120, verbose_name='How many drivers race in a F1 race?'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question8',
            field=models.CharField(max_length=120, verbose_name='How many championships has Lewis Hamilton won?'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question9',
            field=models.CharField(max_length=120, verbose_name='How many championships has Lewis Hamilton won?'),
        ),
    ]
