# Generated by Django 3.2.3 on 2021-07-04 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parte2', '0002_auto_20210704_0307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(max_length=120, verbose_name='From 1 to 10 how would you rate the level of clarity in the questions presented in the quizz section of this website?')),
                ('question2', models.CharField(max_length=120, verbose_name='From 1 to 10 how would you rate the level of rigor in the questions presented in the quizz section of this website?')),
                ('question3', models.CharField(max_length=120, verbose_name='Reagarding the website itself how would you qualify(from 1 to 10) the level of precision regarding the information displayed?')),
                ('question4', models.CharField(max_length=120, verbose_name='Do you think this website covers a wide range of topics related to F1?')),
                ('question5', models.CharField(max_length=120, verbose_name='Do you believe this website focused on important details about F1. How focused would you say it was from 1 to 10 ?')),
                ('question6', models.CharField(max_length=120, verbose_name='How useful do you think this website was?')),
                ('question7', models.CharField(max_length=120, verbose_name='Does this website make sense, as in, the various parts make sense as a whole? Please give us your opinion?')),
                ('question8', models.CharField(max_length=120, verbose_name="As amazing as this site is i'm sure there are ways we can improve it further. Please give us your ideas on how to improve it?")),
            ],
        ),
    ]
