# Generated by Django 3.2.3 on 2021-07-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parte2', '0003_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='question1',
            field=models.IntegerField(max_length=10, verbose_name='From 1 to 10 how would you rate the level of clarity in the questions presented in the quizz section of this website?'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='question2',
            field=models.IntegerField(max_length=10, verbose_name='From 1 to 10 how would you rate the level of rigor in the questions presented in the quizz section of this website?'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='question3',
            field=models.IntegerField(max_length=10, verbose_name='Reagarding the website itself how would you qualify(from 1 to 10) the level of precision regarding the information displayed?'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question1',
            field=models.IntegerField(max_length=15, verbose_name='How many teams race in Formula 1?'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question10',
            field=models.CharField(max_length=120, verbose_name="Who is Sebastian Vettel's teammate?"),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question2',
            field=models.IntegerField(max_length=50, verbose_name='How many championships has Lewis Hamilton won?'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question7',
            field=models.IntegerField(max_length=30, verbose_name='How many drivers race in a F1 race?'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question8',
            field=models.IntegerField(max_length=30, verbose_name='How many drivers are from Europe?'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question9',
            field=models.CharField(max_length=120, verbose_name='Who is the oldest driver?'),
        ),
    ]
