# Generated by Django 3.2.3 on 2021-07-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parte2', '0004_auto_20210704_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='question1',
            field=models.IntegerField(verbose_name='How many teams race in Formula 1?'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question10',
            field=models.IntegerField(verbose_name="Who is Sebastian Vettel's teammate? - 1 -> Kimi Raikkonen  2-> Lance Stroll 3-> Charles Leclerc"),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question2',
            field=models.IntegerField(verbose_name='How many championships has Lewis Hamilton won?'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question3',
            field=models.IntegerField(verbose_name='Which Team has won the most championships? - 1 -> Mercedez  2 -> Ferrari  3 -> Williams'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question4',
            field=models.IntegerField(verbose_name='For which team does Nicholas Latifi race for? - 1 -> Williams  2 -> Ferrari  3 -> Red Bull'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question5',
            field=models.IntegerField(verbose_name='What color is the Ferrari car? - 1 -> Blue  2 -> Red  3-> Green'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question6',
            field=models.IntegerField(verbose_name="Where is the location of Haas's base? - 1 -> USA  2-> Italy  3-> Germany"),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question7',
            field=models.IntegerField(verbose_name='How many drivers race in a F1 race?'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question8',
            field=models.IntegerField(verbose_name='How many drivers are from Europe?'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question9',
            field=models.IntegerField(verbose_name='Who is the oldest driver? - 1 -> Fernando Alonso  2-> Yuki Tsunoda 3-> Kimi Raikkonen '),
        ),
    ]
